### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by onno-timmerman** [code-on/wagtail-staging#3]
I would like that this is updated with latest code (see code-on website) 
This should be a plugin on PIP and have a small instructional html page.

I'll make sure the plugin is on Wagtail plugins and linked and announce it in the community.

Why:
This is handy tool for many people. And making something open source + link to Code-on website on the page will be a high quality backlink.

**Comment by Alex-Sichkar** [comment]
Cleaning up old issues; reopen if it's still relevant
