### ISSUE TITLE
Add imagemagick morgify

### ISSUE THREAD

**Issue by onno-timmerman** [code-on/wagtail-staging#4]
When doing save staging and this is done the tool should ask if you want to compress the staging image files.
magick morgify * %5

I do this to make all jpg as small as possible. Problem is sometimes a PNG but little we can do about it.

It needs to check if imagemagick is installed if not say please install
It needs to give warning that all files that are copied to staging folder will be morgified. That the original files will not be overwritten

**Comment by Alex-Sichkar** [comment]
Cleaning up old issues; reopen if it's still relevant
